backend:
    name: github
    repo: 1000tech/SAPro
    branch: main
    base_url: /api/oauth
    auth_endpoint: auth

locale: 'de'
local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

i18n:
    structure: multiple_folders
    locales: [de, en, ru]
    default_locale: de

collections:
  - name: "home"
    label: "Startseite"
    description: "Inhalte der Startseite je Sprache"
    folder: "content"
    media_folder: "/public/uploads"
    public_folder: "/uploads"
    path: "{{locale}}/home"
    create: false
    i18n: true
    filter:
      field: "type"
      value: "home"
    fields:
      - { label: "Typ", name: "type", widget: "hidden", default: "home" }
      - { label: "Titel", name: "title", widget: "string", i18n: true }
      - { label: "Untertitel (Hero)", name: "hero_subtitle", widget: "string", i18n: true, required: false }
      - label: "Buttons (Hero)"
        name: "hero_buttons"
        widget: "object"
        collapsed: false
        fields:
          - { label: "Prim\u00e4r-Button", name: "primary_label", widget: "string", required: false }
          - { label: "Sekund\u00e4r-Button", name: "secondary_label", widget: "string", required: false }
      - { label: "Abschnittstitel \u2013 Leistungen", name: "services_title", widget: "string", i18n: true, required: false }
      - label: "Leistungen"
        name: "services"
        widget: "list"
        collapsed: false
        i18n: true
        fields:
          - { label: "Icon", name: "icon", widget: "string" }
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Beschreibung", name: "description", widget: "text" }
      - { label: "Abschnittstitel \u2013 Warum wir", name: "why_title", widget: "string", i18n: true, required: false }
      - label: "Vorteile"
        name: "features"
        widget: "list"
        collapsed: false
        i18n: true
        fields:
          - { label: "Icon", name: "icon", widget: "string" }
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Text", name: "text", widget: "text" }

  - name: "pages"
    label: "Seiten"
    label_singular: "Seite"
    description: "Website-Seiten erstellen und bearbeiten"
    folder: "content"
    media_folder: "/public/uploads"
    public_folder: "/uploads"
    path: "{{locale}}/{{slug}}"
    create: true
    slug: "{{slug}}"
    i18n: true
    filter:
      field: "type"
      value: "page"
    fields:
      - { label: "Typ", name: "type", widget: "hidden", default: "page" }
      - { label: "Titel", name: "title", widget: "string", i18n: true }
      - { label: "Inhalt", name: "body", widget: "markdown", i18n: true }

  - name: "menus"
    label: "Men\u00fc"
    description: "Hauptmen\u00fceintr\u00e4ge je Sprache bearbeiten"
    files:
      - label: "Deutsch"
        name: "menu_de"
        file: "content/de/_menu.md"
        fields:
          - { label: "Abschnittstitel \u2013 Leistungen", name: "services_title", widget: "string", required: false }
          - label: "Men\u00fcpunkte"
            name: "items"
            widget: "list"
            collapsed: false
            summary: "{{fields.label}} \u2192 {{fields.path}}"
            fields:
              - { label: "Bezeichnung", name: "label", widget: "string" }
              - { label: "Pfad", name: "path", widget: "string", hint: "Der f\u00fchrende / wird automatisch erg\u00e4nzt" }
          - { label: "Kontakt Titel", name: "contact_title", widget: "string", required: false }
          - { label: "Telefon", name: "phone", widget: "string", required: false }
          - { label: "E-Mail", name: "email", widget: "string", required: false }
      - label: "Englisch"
        name: "menu_en"
        file: "content/en/_menu.md"
        fields:
          - { label: "Abschnittstitel \u2013 Leistungen", name: "services_title", widget: "string", required: false }
          - label: "Men\u00fcpunkte"
            name: "items"
            widget: "list"
            collapsed: false
            summary: "{{fields.label}} \u2192 {{fields.path}}"
            fields:
              - { label: "Bezeichnung", name: "label", widget: "string" }
              - { label: "Pfad", name: "path", widget: "string", hint: "Der f\u00fchrende / wird automatisch erg\u00e4nzt" }
          - { label: "Kontakt Titel", name: "contact_title", widget: "string", required: false }
          - { label: "Telefon", name: "phone", widget: "string", required: false }
          - { label: "E-Mail", name: "email", widget: "string", required: false }
      - label: "Russisch"
        name: "menu_ru"
        file: "content/ru/_menu.md"
        fields:
          - { label: "Abschnittstitel \u2013 Leistungen", name: "services_title", widget: "string", required: false }
          - label: "Men\u00fcpunkte"
            name: "items"
            widget: "list"
            collapsed: false
            summary: "{{fields.label}} \u2192 {{fields.path}}"
            fields:
              - { label: "Bezeichnung", name: "label", widget: "string" }
              - { label: "Pfad", name: "path", widget: "string", hint: "Der f\u00fchrende / wird automatisch erg\u00e4nzt" }
          - { label: "Kontakt Titel", name: "contact_title", widget: "string", required: false }
          - { label: "Telefon", name: "phone", widget: "string", required: false }
          - { label: "E-Mail", name: "email", widget: "string", required: false }

  - name: "texts"
    label: "Globale Texte"
    description: "Kopf- und Fu\u00dfzeilentexte der Website bearbeiten"
    files:
      - label: "Deutsch"
        name: "texts_de"
        file: "content/de/_texts.md"
        fields:
          - { label: "404 Titel", name: "error_404_title", widget: "string", hint: "\u00dcberschrift, die auf der 404-Fehlerseite angezeigt wird" }
          - { label: "404 Beschreibung", name: "error_404_description", widget: "string", hint: "Erkl\u00e4rungstext f\u00fcr die 404-Fehlerseite" }
          - { label: "404 Button-Text", name: "error_404_button", widget: "string", hint: "Beschriftung des Buttons auf der 404-Fehlerseite" }
      - label: "Englisch"
        name: "texts_en"
        file: "content/en/_texts.md"
        fields:
          - { label: "404 Titel", name: "error_404_title", widget: "string", hint: "\u00dcberschrift, die auf der 404-Fehlerseite angezeigt wird" }
          - { label: "404 Beschreibung", name: "error_404_description", widget: "string", hint: "Erkl\u00e4rungstext f\u00fcr die 404-Fehlerseite" }
          - { label: "404 Button-Text", name: "error_404_button", widget: "string", hint: "Beschriftung des Buttons auf der 404-Fehlerseite" }
      - label: "Russisch"
        name: "texts_ru"
        file: "content/ru/_texts.md"
        fields:
          - { label: "404 Titel", name: "error_404_title", widget: "string", hint: "\u00dcberschrift, die auf der 404-Fehlerseite angezeigt wird" }
          - { label: "404 Beschreibung", name: "error_404_description", widget: "string", hint: "Erkl\u00e4rungstext f\u00fcr die 404-Fehlerseite" }
          - { label: "404 Button-Text", name: "error_404_button", widget: "string", hint: "Beschriftung des Buttons auf der 404-Fehlerseite" }
